packages:
  # all packages in direct subdirs of packages/
  - 'packages/*'

catalog:
  typescript: ~5.5.2
  "@types/node": ^20.3.1
  "@types/express": ^5.0.0
  "prettier": "^3.0.0"
  "date-fns": "4.1.0"
  "@date-fns/tz": "1.2.0"
  rxjs: ^7.8.1
